# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(max_length=100)),
                ('rooms', models.FloatField()),
                ('price', models.IntegerField(verbose_name=0)),
                ('link', models.CharField(max_length=1000)),
                ('date', models.DateField()),
            ],
        ),
    ]
